version: '3'
services:
  # - Minecraft server config
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    ports:
      - "25565:25565"
    volumes:
      - ".:/data"
    environment:
      # Base config
      EULA: "TRUE"
      CONSOLE: "false"
      # Server config
      ENABLE_RCON: "true"
      RCON_PASSWORD: "testing"
      RCON_PORT: 28016
      SERVER_PORT: 25565
      VERSION: 1.15
      ICON: "https://images-na.ssl-images-amazon.com/images/I/81eVnOh4UJL._SY355_.jpg"
      SERVER_NAME: "ChaTea"
      MOTD: "Eternal Blue, Avenue 23"
      MODE: "survival"
      OVERRIDE_SERVER_PROPERTIES: "true"
      # Build config
      MEMORY: 6G
      TYPE: SPIGOT
      ENABLE_COMMAND_BLOCK: "true"
      GENERATE_STRUCTURES: "true"
      MAX_BUILD_HEIGHT: 128
      VIEW_DISTANCE: 8
      # Game config
      ONLINE_MODE: "false"
      ALLOW_NETHER: "true"
      FORCE_GAMEMODE: "true"
      OPS: "fhivemind"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
    command: --noconsole
    # Configure machine
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 6500M
        reservations:
          cpus: '2.0'
          memory: 6500M
  # - RCON config
  rcon:
    image: itzg/rcon
    container_name: minecraft_rcon
    ports:
      - "4326:4326"
      - "4327:4327"
    volumes:
      - "rcon:/opt/rcon-web-admin/db"

volumes:
  mc:
  rcon: