version: '3'
# Other docker-compose examples in /examples

services:
  minecraft:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: minecraft
    ports:
      - "24321:24321"
    volumes:
      - "mc:/data"
    environment:
      EULA: "TRUE"
      CONSOLE: "true"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "testing"
      RCON_PORT: 28016
      SERVER_PORT: 24321
      VERSION: 1.15
      MAX_MEMORY: 5G
      MAX_BUILD_HEIGHT: 256
      VIEW_DISTANCE: 15
      OVERRIDE_SERVER_PROPERTIES: "true"
      OPS: "fhivemind"
      ICON: "https://images-na.ssl-images-amazon.com/images/I/81eVnOh4UJL._SY355_.jpg"
      ALLOW_NETHER: "true"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
      ENABLE_COMMAND_BLOCK: "true"
      FORCE_GAMEMODE: "true"
      GENERATE_STRUCTURES: "true"
      MODE: "survival"
      MOTD: "Eternal Blue, Avenue 23"
    restart: always
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 6000M
        reservations:
          cpus: '4'
          memory: 5500M
  rcon:
    image: itzg/rcon
    container_name: minecraft_rcon
    ports:
      - "4326:4326"
      - "4327:4327"
    volumes:
      - "rcon:/opt/rcon-web-admin/db"

volumes:
  mc:
  rcon: